### ISSUE TITLE
Speed up connection refresh

### ISSUE THREAD

**Issue by Revel8804** [odwdinc/Python-SimConnect#34] opened 2020-09-20 02:24 UTC
I would like to do some testing, but i can not seem to figure out how to speed up the connection and refreshes to simconnect.

It looks like the default is 2 sec.

**Comment by hankhank10** [comment] 2020-09-20 06:50
Do you mean in the web app?

**Comment by odwdinc** [comment] 2020-09-20 16:59
See the updated [README](https://github.com/odwdinc/Python-SimConnect/blob/master/README.md)
Duplicate of #30

**Closed as completed by odwdinc** 2020-09-20 16:59 UTC
