### ISSUE TITLE
Web app: development roadmap

### ISSUE THREAD

**Issue by hankhank10** [odwdinc/Python-SimConnect#13] opened 2020-09-06 22:52 UTC
I have created a Trello board for the features that I plan to add to the web app and where there are bugs which need fixing.

I have colour coded the issues based on whether they are front end (for me to do) and where I will need help on the back end.

If you would like to be added to the Trello board to contribute then please let me know.

https://trello.com/b/lYT0cfTt/glass-cockpit

**Comment by odwdinc** [comment] 2020-09-07 00:25
I think I have https://trello.com/c/Nwc0CPZi fixed with https://github.com/odwdinc/Python-SimConnect/blob/825ef813469b4b2819e6155cd12d7dbc0816ac4e/local_example_set_sim_var_data.py#L40-L44

each request.outData can now be used as  in/out
with set_data
https://github.com/odwdinc/Python-SimConnect/blob/825ef813469b4b2819e6155cd12d7dbc0816ac4e/SimConnect/SimConnect.py#L1101
and get_data
https://github.com/odwdinc/Python-SimConnect/blob/825ef813469b4b2819e6155cd12d7dbc0816ac4e/SimConnect/SimConnect.py#L1118

see
https://github.com/odwdinc/Python-SimConnect/blob/825ef813469b4b2819e6155cd12d7dbc0816ac4e/local_example.py#L66-L73

**Comment by Heiss** [comment] 2020-09-07 07:00
Wow. What a nice look. :) That is cool.

You do not need the trello board, because Github has such features. It is called projects. Maybe @odwdinc can give you the rights to make it happen here.

Also i would suggest that you extract your web app (not your web api) into a separate module and import the SimConnect module. It would be more pythonic and maintainable. With the current approach, you get with a simple `pip install SimConnect` two things... The binding to SimConnect AND a webserver, which does two things (provides data through an api and provides an UI to consume this api). 

With pypi, you can configure the installation process so, that the web api of the binding will only be installed, when you specify a special tag: e.g. `pip install SimConnect[web]`. We can implement the web api, so that it will only be available through the module, when you install the `web`-package. This guarantees, that nobody gets data garbage, that he will never use. In the default process, only the SimConnect binding will be installed through pip withouth flask or any web stuff.

Your javascript-stuff could be an example for such a consumption of the web api. In my opinion, it should not be maintained in this repository, when you want to make it bigger and to provide an easy access for your user.

**Comment by hankhank10** [comment] 2020-09-07 09:52
Thank you.

Would it be possible to abstract the API further to make it more straightforward for end users to access and set the data? From my perspective it would be ideal to have a simple

get_sim_data(datapoint_name)

and

set_sim_data(datapoint_name, value)

functions which handle the raising of the request and gathering/setting the data.

With regard to splitting the repo, for the moment given we are developing quickly I would prefer to keep it in one if that's ok with others for simplicity. Once things slow down we can consider splitting the HTML/JS elements out (although actually I think they're a pretty clean and lightweight example of how to use the API)

**Comment by Heiss** [comment] 2020-09-07 12:27
Yeah it is cool for me to let the html in this repo at the current stage of development. It was a suggestion for better reusability. 👍 

I am working on an API to make it easier to work with the SimConnect

I would prefer this way:

```python
from SimConnect import Plane
pl = Plane()
print("my altitude: {}".format(pl.altitude) # my altitude: 5.678743
pl.gear_toggle # toggles gear
pl.pitch = 1 # pitch the nose to 1 degree
print(pl.pitch) # 1
pl.pitch += 90
print(pl.pitch) # 91
```

The problem is, that the calls to SimConnect are asynchroneous and my examples are synchroneous calls. This means, we need an abstraction layer for this. For this purpose, the python API implements asyncio with async methods and await. My idea is to cache everything from SimConnect to provide a sync method to end user (like my example above) and an async method to end user, which he can awaits.

```python
from SimConnect import Plane
pl = Plane()
print("my altitude: {}".format(await pl.async_altitude) # my altitude: 5.3445678
```

Await guarantees, that the user gets always the current value from SimConnect, but he needs to use asyncio to use async-methods. This is the same approach, which Home Assistant uses (https://developers.home-assistant.io/docs/asyncio_working_with_async/).

For a lower api call i would prefer something like this

```python
from SimConnect import Plane, Event, Measurement

pl = Plane()
print("my altitude: {}".format(pl.get(Measurement.Altitude)) # my altitude: 5.678743
```

Event and Measurement are Enums, which abstracts the names and definition id's corresponding to the official SimConnect API documentation.

Also here an async-methods:

```python
from SimConnect import Plane, Event, Measurement

pl = Plane()
print("my altitude: {}".format(await pl.async_get(Measurement.Altitude)) # my altitude: 5.3445678
```

**Comment by odwdinc** [comment] 2020-09-08 00:06
@hankhank10  and @Heiss 
Did an overhaul on the API I think it more in line with what you are wanting. There is now only a small loop in 
https://github.com/odwdinc/Python-SimConnect/blob/33c5d7f7cf47898181b602234e8c7c64bd40d49b/SimConnect/SimConnect.py#L222-L233

This could be replace with some async bits but not 100% on how yet.

**Comment by hankhank10** [comment] 2020-09-08 00:30
That's great, will make it much easier to reference individual data points.

Does the existing method as written in https://github.com/odwdinc/Python-SimConnect/blob/master/glass_server.py still work to get larger data sets in one go?

**Comment by odwdinc** [comment] 2020-09-08 01:17
@hankhank10  Tested data/[autopilot, flaps, airspeed, ui ] all seem to work as expected.  All other routes where tested and confirmed working.

Very excited to get data back into the sim. Thank you once more for your work!

**Comment by odwdinc** [comment] 2020-09-08 01:21
@hankhank10  Quick sample for you on request_holder.[get/set]

```
sm = SimConnect()
request_ui = sm.new_request_holder()
request_ui.add('ALTITUDE', (b'PLANE ALTITUDE', b'feet'))
request_ui.add('LATITUDE', (b'PLANE LATITUDE', b'degrees'))
request_ui.add('LONGITUDE', (b'PLANE LONGITUDE', b'degrees'))
request_ui.add('thr', (b'GENERAL ENG THROTTLE LEVER POSITION:1', b'Percent'))

print(request_ui.get("thr"))
request_ui.set("thr", 25)
print(request_ui.get("thr"))
sleep(5)
request_ui.set("thr", 100)
print(request_ui.get("thr"))
sm.exit()
```

**Comment by hankhank10** [comment] 2020-09-08 09:24
In addition to set_data() it would be helpful to have a toggle_data() function for the Boolean variables.

For instance when hitting the autopilot master switch it would be helpful to have it just turn on/off without having to get_data then set_data to the opposite

**Comment by odwdinc** [comment] 2020-09-08 14:51
Just an FYI none of the Requests [Aircraft Autopilot Data](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526981(v=msdn.10)#aircraft-autopilot-data) Simulation Variable are Settable via SDK, AKA read only.

Need to use the Event system.
For full list of Autopilot Events see [Aircraft Automatic Flight Systems / Autopilot](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526980(v=msdn.10)#aircraft-automatic-flight-systems--autopilot)
Sample:
```
sm = SimConnect()
AP_MASTER = Event(b'AP_MASTER', sm)
THROTTLE1_SET = Event(b'THROTTLE1_SET', sm)

# Send Event with value
THROTTLE1_SET(1500).

# Send Event Toggle
AP_MASTER()
sm.exit()
```

my hope is to get a more affected class system for accessing them.

**Comment by hankhank10** [comment] 2020-09-09 06:15
I really like the interface you've built for triggering events and getting/setting variables in in local_example.py, for example:

````
ae = AircraftEvents(sm)
AP_MASTER = ae.find("AP_MASTER")
AP_MASTER()
````

and 

````
aq = AircraftRequests(sm)
print(aq.Position_and_Speed.get('PLANE_ALTITUDE'))
````


Will this be the preferred way for triggering events and accessing variables going forward? Is is possible to set variables that way was well? For instance:

`aq.Position_and_Speed.set('PLANE_ALTITUDE', 1000)`

If so, I will move my code across to this model as it seems much neater.

Is there an advantage in performance terms to using the previous request_holder methodolody?

**Comment by hankhank10** [comment] 2020-09-09 12:00
I've got this working pretty nicely now and have raised a pull request. I still have some testing to do in the simulator, but I think it should all run ok.

New features:

Autopilot variables can be set from the simulator.

I've also built out an "emergencies" tab which, for instance, allows you to simulate an electrical failure or engine failure. I'm also working on an engine fire option.

I've also added an aviation overlay to the map which gives the option to show eg airports and restricted airspace.

A few photos:

<img width="1425" alt="Screenshot 2020-09-09 at 12 54 43" src="https://user-images.githubusercontent.com/25515609/92595497-5ef29e80-f29c-11ea-8939-ad00be170ee0.png">
<img width="1430" alt="Screenshot 2020-09-09 at 12 54 21" src="https://user-images.githubusercontent.com/25515609/92595502-61ed8f00-f29c-11ea-9d70-64e2f015abd0.png">

**Comment by odwdinc** [comment] 2020-09-09 14:48
@hankhank10 I think Events are good, may rework requests a bit to make more inline with Events. nothing should change on your side.
and yes it's possible to set variables that way was well. Should just work if the requests is settable.
amazing work thanks agen.

**Closed as completed** 2020-09-20 17:00 UTC
